language: python
python:
  - "3.4"
install: 
  - sudo apt-get update
  - sudo apt-get install python-qt4 mplayer lame libportaudio2
  - pip install nose
  - pip install coveralls

script: nosetests ./tests --with-coverage --cover-package=./anki

after_success:
  - coveralls
